--- Eliminación de llave foránea de "category_id" de la entidad de productos.
ALTER TABLE catalog.tbl_products
DROP CONSTRAINT tbl_products_category_fkey;

--- Eliminación de la columna "category id".
ALTER TABLE catalog.tbl_products
DROP COLUMN category_id;

--- Eliminación de la PK de tbl_categories.
ALTER TABLE catalog.tbl_categories
DROP CONSTRAINT PK_tbl_categories;

--- Eliminación de id de tbl_categories.
ALTER TABLE catalog.tbl_categories
DROP CONSTRAINT id;

--- Creación de nueva columna id de tipo int identity.
ALTER TABLE catalog.tbl_categories
ADD COLUMN id integer GENERATED BY DEFAULT AS IDENTITY;

--- Creación de PK en id de tbl_categories.
ALTER TABLE catalog.tbl_categories
ADD CONSTRAINT tbl_categories_pkey PRIMARY KEY (id);

--- Creación de nueva columna category_id de tipo int en tbl_products.
ALTER TABLE catalog.tbl_products
ADD COLUMN category_id integer NOT NULL;

--- Creación de nueva FK en category_id de tbl_products.
ALTER TABLE catalog.tbl_products
ADD CONSTRAINT tbl_products_category_fkey
FOREIGN KEY (category_id)
REFERENCES tbl_categories(id)
ON DELETE RESTRICT;